### ISSUE TITLE
Package not found on conda 

### ISSUE THREAD

**Issue by ouzmno** [epogrebnyak/justpath#19]
Hi there,

I tried to install the package in different conda environments, first in the one with py==3.9.15 and another one with py==3.11.0.

However both environments failed to find the package. 

I am using miniforge package manager by the way.

Does anyone know about the incident? Thanks!

**Comment by epogrebnyak** [comment]
Not sure how package gets to conda, it is not published on conda as of now. 

But you can install with pip like pip install justpath or install from URL.

**Comment by ouzmno** [comment]
> Not sure how package gets to conda, it is not published on conda as of now.
> 
> But you can install with pip like pip install justpath or install from URL.

Thank you! I think my request has been solved. So I will close It now.
