### ISSUE TITLE
~ may not expand properly

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/justpath#21]
Possibly due to conda. Maybe need to call expanduser() before resolve().

**Comment by jrzkaminski** [comment]
A screenshot demonstrating the problem
![Screenshot_20240311_233957](https://github.com/epogrebnyak/justpath/assets/86363785/e32d128c-ef72-4b24-ac01-535a162bd994)

**Comment by sammcj** [comment]
I found this as well:

<img width="1216" alt="image" src="https://github.com/epogrebnyak/justpath/assets/862951/48a97ea9-1df0-4f8c-acc3-ab937000132a">

**Comment by sammcj** [comment]
likewise with `*`:

<img width="711" alt="image" src="https://github.com/epogrebnyak/justpath/assets/862951/33d4e6a6-e993-428c-9965-5fb85f5ddefb">

**Comment by jrzkaminski** [comment]
Now that seems funny

![photo_2024-03-11_23-51-10](https://github.com/epogrebnyak/justpath/assets/86363785/1b718cad-e848-44df-9cca-4346c5a2a97b)

**Comment by sammcj** [comment]
What is this? Javascript?! 🤣

**Comment by epogrebnyak** [comment]
I should add abspath before checking the directory exists, as Python takes "~" and "*" literally when checking if path exists.

**Comment by epogrebnyak** [comment]
@jrzkaminski - please see if `pip install -U justpath` has proper behavior

**Comment by epogrebnyak** [comment]
@sammcj - `fzf/*/bin` not supported yet, justpath will treat it literally. Perhaps need separate issue to be open.

Will close this issue one someone approves `~` is treated correctly.

**Comment by jrzkaminski** [comment]
@epogrebnyak seems like the problem has been solved
![Screenshot_20240318_125151](https://github.com/epogrebnyak/justpath/assets/86363785/68a64d2c-ef91-4429-b854-45d3eca37bf6)

**Comment by epogrebnyak** [comment]
Nice, thanks for following up! Will close the issue as completed.
