### ISSUE TITLE
add badge for Python Bytes podcast

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/justpath#26]
[![podcast](https://img.shields.io/badge/Python_Bytes-377-D7F9FF?logo=applepodcasts&labelColor=blue)](https://www.youtube.com/watch?v=eWnYlxOREu4&t=125s)

@mikeckennedy - how do you like the badge? Thinking of putting the badge into a readme.

**Comment by mikeckennedy** [comment]
I love it! I'd be proud to see it in the readme. How did you make it? Can others who have featured projects get one easily?

**Comment by epogrebnyak** [comment]
The badge is made in markdown, it is based on  shields.io service, can also use badgegen service. 

```
[![Python Bytes](https://img.shields.io/badge/Python_Bytes-377-D7F9FF?logo=applepodcasts&labelColor=blue)](https://www.youtube.com/watch?v=eWnYlxOREu4&t=125s)
```

One passes the parameters of the badge and gets a SVG as output. I think it is good idea for projects mentioned in podcast to put a badge together with a link either to video or to podcast link.

**Comment by mikeckennedy** [comment]
Cool, thanks for the the tip! I'll mention this on the show this week.

**Comment by epogrebnyak** [comment]
One other thing I thought about you could make an awesome-pybytes repo and mention projects there, for example by category - and do it with badges. You do have a neat page for the episodes but a repo with just one README.md can be something  more closer to code and an extra showcase 

I can make you a draft of the awesome-pybytes page then way I'd have designed it - you can adopt it if you liked.

**Comment by epogrebnyak** [comment]
https://www.youtube.com/live/4oALfE-zDf8?si=mQuU1S08DMW3xejv

**Comment by mikeckennedy** [comment]
Hey @epogrebnyak the idea of awesome pb repo is great. We had something like that for Talk Python for a little bit. It went well for 6 months then the person running it lost interest and I don't have the time to put into it. I think the PB one would take more work and probably suffer the same fate. But I'll keep it in mind for sure.

**Comment by epogrebnyak** [comment]
Understood, good there was  a test!

**Comment by epogrebnyak** [comment]
As we gave the badge in README closing this issue now.

**Comment by mikeckennedy** [comment]
Thanks and that badge looks great. I'll be giving it a shoutout next week on the show.
