### ISSUE TITLE
`sep()` can be replaced with `os.pathsep`

### ISSUE THREAD

**Issue by evilgordita** [epogrebnyak/justpath#4]
`sep()` can be replaced with [`os.pathsep`](https://docs.python.org/3/library/os.html#os.pathsep)

Python has you covered there. Cheers!

**Comment by epogrebnyak** [comment]
Good call, thanks! I knew `os.sep` existed, but not `os.pathsep`. Fixed in commit above, surely cleaner without `sep()`.
