### ISSUE TITLE
`show --json` may deviate from `show`

### ISSUE THREAD

**Issue by djhenderson** [epogrebnyak/justpath#7]
I installed justpath in a Python 3.12.1 virtual environment. I usually look at a new app's help message:

```
> justpath --help
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "D:\Users\user\dir\venv\Scripts\justpath.exe\__main__.py", line 7, in <module>
    sys.exit(typer_app())
             ^^^^^^^^^^^

RuntimeError: Type not yet supported: str | None

```

Running `justpath` gives the same error.

**Comment by djhenderson** [comment]
BTW: I am running Windows 10 Pro

```
> ver

Microsoft Windows [Version 10.0.19045.3930]

```

**Comment by epogrebnyak** [comment]
Thank you for writing back, I have had a similar error in development, that is due to Typer behavior, but it went away. 

Does the error show on startup or particular command? 

Got an idea to fix, will update soon.

**Comment by djhenderson** [comment]
I think it must be during startup because the failure happens for both `justpath --help` and `justpath `commands.

**Comment by epogrebnyak** [comment]
> I think it must be during startup because the failure happens for both `justpath --help` and `justpath `commands.

Try updating to `pip install justpath==0.0.8` - and see if it works now for you. Hard to say why behavior diverged as Typer version is supposed to be pinned anyways, but I simplified code to exclude the type `str | None`, it is as simple as `str` now.

**Comment by epogrebnyak** [comment]
Or even `pip install justpath==0.0.9`

**Comment by djhenderson** [comment]
thank you

**Comment by epogrebnyak** [comment]
Does it work now?

**Comment by djhenderson** [comment]
yes. Something to look at: the JSON output includes the current directory as the last item in the list; the plain output from show does not. The current directory is usually not explicitly included in the windows PATH, but it is assumed by `command.com` to be the last folder searched. On `*nix`, we have to use `./file` to execute `file` from the current directory.

**Comment by epogrebnyak** [comment]
> Something to look at: the JSON output includes the current directory as the last item in the list; the plain output from show does not.

This is on Windows, right? `justpath show` vs `justpath show --json`?

**Comment by epogrebnyak** [comment]
If it is linux, can you try: 
```
justpath show --json | jq .[-1]
justpath show | tail -1 
```

**Comment by djhenderson** [comment]
My mistake, my old eyes must be failing me. 

My path seems to have a trailing semicolon.  I did not think I had that in my path. So it looks like justpath is working as expected. All my issues are now resolved. I think you can close this issue.

**Comment by epogrebnyak** [comment]
Thank you for giving justpath such close examination and your attention, hope you will like the upcoming features. I'm changing the data model a bit, so the output is becoming a bit more rich (eg another color for duplicate directories).
